services:
    streamlit-app:
        build: ./
        command: streamlit run /opt/src/visualization.py --server.port 8501
        volumes:
            - ./src:/opt/src
            - ./data:/opt/data
        ports:
            - 8501:8501
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
    flask-app:
        build: ./
        command: python3 /opt/src/retrain_app.py
        volumes:
            - ./src:/opt/src
            - ./data:/opt/data
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

networks:
  default:
    name: data_platform
    external: true